### ISSUE TITLE
Astronomer -0.23.11  Helm Chart - fluentd config concatenation issue

### ISSUE THREAD

**Issue by prasadrayudu** [astronomer/astronomer#1030]
Issue:- Implemented 2 new params for fluend configuration has concatenation issue --
Earlier we had a PR which was introduced two more parameters based on customer request which is  - "path" and "use_server_side_encryption" - It was released in 0.23.11
https://www.astronomer.io/docs/enterprise/v0.23/monitor/logs-to-s3

Moreoever, we have brought to notice by customer raising ticket that there is concatenation issue - we have checked and confirmed this is a bug which needs to be fixed.

Please check the below ticket for the complete ref.
ref: https://astronomer.zendesk.com/agent/tickets/3700

**Comment by vishwas-astro** [comment]
@krisdock @prasadrayudu can you please move this to the astronomer/issues repo so it can be tracked in the Astro Platform sprint board?

**Comment by krisdock** [comment]
opened: https://github.com/astronomer/issues/issues/2687

closing this
