### ISSUE TITLE
Please stop spamming me, I never subscribed to your marketing list.

### ISSUE THREAD

**Issue by da-edra** [astronomer/astronomer#1120]
Hello! Your marketing team is using very shady practices to make look at your product. Your marketing team used my public GitHub address to subscribe me to a marketing list I never requested to be a part of.

What you're doing is spam, please stop doing it, it's super annoying.

![Screenshot_2021-06-04_13-33-37](https://user-images.githubusercontent.com/10160626/120847725-7ca61900-c539-11eb-8263-250895465fa8.png)

**Comment by paolaperaza** [comment]
Hi there, @da-edra - thank you for reaching out, and I'm sorry to hear you received email from us without ever formally granting Astronomer consent to send you content. As a user of the internet that also gets way too many unsolicited emails, I couldn't agree more with your frustration.

We've been hiring a handful of new folks to our marketing team and got our wires crossed with some of our listservs. I've spoken to our Director of Growth Marketing and he assured me that you've been removed from our newsletter and should not expect to receive any more (unsolicited) communication from us.

I hope this doesn't forever dissuade you from exploring our product/team. I'll go ahead and close out this GH issue for now, but if you ever have any questions or want to learn more about Astronomer, please don't hesitate to reach out to me directly at `paola@astronomer.io`. We'd love to win you back 😊

**Comment by da-edra** [comment]
Thanks so much for your comprehension! <3
