### ISSUE TITLE
Issue with apiVersion helpers and AWS EKS

### ISSUE THREAD

**Issue by jplanza-gr** [astronomer/astronomer#1158]
In #1122 , the apiVersion helper was updated to handle the change from "extensions/v1beta1" to "networking.k8s.io/v1" in K8S 1.20.  On an AWS EKS cluster with a K8s Rev of "v1.18.16-eks-7737de", the semverCompare function isn't matching correctly and is falling through to the else condition of "networking.k8s.io/v1".  When attempting to create an ingress based on the v0.25.4 helm chart, I'm seeing this error for each ingress being created:

`Ingress.networking.k8s.io "" not found`

I'm uncertain what the right version specification should be, but I expect that the AWS naming convention is throwing off the test.

Please advise.

References: 

http://masterminds.github.io/sprig/semver.html
https://github.com/astronomer/astronomer/blob/master/templates/_apivers.tpl#L18

**Comment by rbankston** [comment]
This is an issue with Argo not able to template with --kube-version correctly. This feature is built into helm 3.6.0 but not yet packaged in Argo.

Solutions:

* Upgrade cluster to 1.19 where the annotation is support
* Override template that uses that versioning
* Wait for Argo that includes helm v3.6.0

Relevant Argo github links:

Issue: https://github.com/argoproj/argo-cd/issues/5833
Pull Request: https://github.com/argoproj/argo-cd/pull/6359
