### ISSUE TITLE
K8s v1.22 support

### ISSUE THREAD

**Issue by whyvez** [astronomer/astronomer#1370]
From looking at your [website](https://docs.astronomer.io/enterprise/version-compatibility-reference/), it looks like you don't yet support k8s `v1.22`. 

We are on GKE and use the `REGULAR` release channel in which `v1.22` is already available.

Can you provide more information about if or when you will support k8s `v1.22`?

**Comment by danielhoherd** [comment]
There is a PR open to add this feature. We are doing extra work to validate it before merging, and updating nginx-ingress from 0.x to 1.1.x. This PR will be merged in the next few weeks. https://github.com/astronomer/astronomer/pull/1401

**Comment by danielhoherd** [comment]
@whyvez 1.22, 1.23 support will be going out with 0.29, and will most likely be back-ported to 0.28 at some point.
