### ISSUE TITLE
Getting error nc: bad address when trying example 

### ISSUE THREAD

**Issue by pedromachados** [astronomer/astronomer#161]
I am trying [this example](https://github.com/astronomer/astronomer/tree/master/examples/airflow-enterprise)  and I see a lot of lines similar to this one in the docker-compose logs:
```
scheduler_1_e8794ab5370f | nc: bad address ''
```
It happens with other services as well. I think it may have to do with a permission issue but I could not figure it out. 

I see the airflow UI but it won't run even a simple DAG (tutorial).

Any ideas?

**Comment by schnie** [comment]
Hey @pedromachados thanks for the heads up. This looks like its due to the way we pass the broker url into the container env vars. It's slightly different between our helm charts and docker-compose. Should have a fix out for this sometime today.

**Comment by schnie** [comment]
Looks like we had a little bit of config drift between our docker-compose and helm service definitions. This issue should be fixed with https://github.com/astronomer/astronomer/commit/774375347943a5f84440c13c26848480926f827b
