### ISSUE TITLE
airflow-enterprise example broken when running airflow 1.10.1

### ISSUE THREAD

**Issue by pedromachados** [astronomer/astronomer#164]
In the current [example](https://github.com/astronomer/astronomer/tree/master/examples/airflow-enterprise), tasks are not picked up. I found a couple of issues:

1) `AIRFLOW__CELERY__CELERY_RESULT_BACKEND` needs to be renamed to `AIRFLOW__CELERY__RESULT_BACKEND` in [airflow.env](https://github.com/astronomer/astronomer/blob/2c11cd05a480bca81b2e0ec110cfb4a3365c2f69/examples/airflow-enterprise/airflow.env#L5)

2) The version of redis backed in your image has a conflict. I was able to make it work by downgrading to `redis>=2.10.5,<3` See https://github.com/puckel/docker-airflow/issues/271

I haven't done any kind of extensive testing but before I changed these two things, the example was not working at all in 1.10.1.

**Comment by schnie** [comment]
@pedromachados thanks for the heads up. We've been focused on our helm deployment and have let these examples slip behind. We are currently building a 1.10.1 image regularly, which is hosted here - https://hub.docker.com/r/astronomerinc/ap-airflow/tags/ (sorry its a little messy with tags at the moment).

We've accounted for these changes here in our helm charts - https://github.com/astronomer/helm.astronomer.io/blob/master/charts/airflow/templates/_helpers.yaml#L40.

So far that's the only major change we've seen. We'll patch the examples up, or accept a PR if you have it working already.

**Comment by pedromachados** [comment]
@schnie @benjamingregory 
I tried `astronomerinc/ap-airflow:master-1.10.1-onbuild` and it still seems to have the wrong redis version. 
I am having to use this in my Dockerfile:

```
FROM astronomerinc/ap-airflow:master-1.10.1-onbuild
RUN pip3 install --no-cache-dir 'redis>=2.10.5,<3'
```
If I don't, here is what I see when I run `docker-compose logs worker`

```
worker_1_a46c8ff2992b | Waiting for host: redis 6379
worker_1_a46c8ff2992b | [2018-12-05 17:12:02,081] {settings.py:174} INFO - setting.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800
worker_1_a46c8ff2992b | [2018-12-05 17:12:03,153] {__init__.py:51} INFO - Using executor CeleryExecutor
worker_1_a46c8ff2992b | [2018-12-05 17:12:06,412] {settings.py:174} INFO - setting.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800
worker_1_a46c8ff2992b | [2018-12-05 17:12:08,413: INFO/MainProcess] Connected to redis://:**@redis:6379/0
worker_1_a46c8ff2992b | [2018-12-05 17:12:08,461: INFO/MainProcess] mingle: searching for neighbors
worker_1_a46c8ff2992b | [2018-12-05 17:12:08,917] {__init__.py:51} INFO - Using executor CeleryExecutor
worker_1_a46c8ff2992b | Starting flask
worker_1_a46c8ff2992b | [2018-12-05 17:12:09,282] {_internal.py:88} INFO -  * Running on http://0.0.0.0:8793/ (Press CTRL+C to quit)
worker_1_a46c8ff2992b | [2018-12-05 17:12:09,565: INFO/MainProcess] mingle: all alone
worker_1_a46c8ff2992b | [2018-12-05 17:12:09,584: INFO/MainProcess] celery@d1dc88440e21 ready.
worker_1_a46c8ff2992b | [2018-12-05 17:12:10,204: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'float' object has no attribute 'items'",)
worker_1_a46c8ff2992b | Traceback (most recent call last):
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
worker_1_a46c8ff2992b |     self.blueprint.start(self)
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
worker_1_a46c8ff2992b |     step.start(parent)
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/celery/bootsteps.py", line 370, in start
worker_1_a46c8ff2992b |     return self.obj.start()
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 316, in start
worker_1_a46c8ff2992b |     blueprint.start(self)
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
worker_1_a46c8ff2992b |     step.start(parent)
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 592, in start
worker_1_a46c8ff2992b |     c.loop(*c.loop_args())
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
worker_1_a46c8ff2992b |     next(loop)
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
worker_1_a46c8ff2992b |     cb(*cbargs)
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/kombu/transport/redis.py", line 1040, in on_readable
worker_1_a46c8ff2992b |     self.cycle.on_readable(fileno)
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/kombu/transport/redis.py", line 337, in on_readable
worker_1_a46c8ff2992b |     chan.handlers[type]()
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/kombu/transport/redis.py", line 724, in _brpop_read
worker_1_a46c8ff2992b |     self.connection._deliver(loads(bytes_to_str(item)), dest)
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 983, in _deliver
worker_1_a46c8ff2992b |     callback(message)
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 632, in _callback
worker_1_a46c8ff2992b |     self.qos.append(message, message.delivery_tag)
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/kombu/transport/redis.py", line 149, in append
worker_1_a46c8ff2992b |     pipe.zadd(self.unacked_index_key, time(), delivery_tag) \
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/redis/client.py", line 2263, in zadd
worker_1_a46c8ff2992b |     for pair in iteritems(mapping):
worker_1_a46c8ff2992b |   File "/usr/lib/python3.6/site-packages/redis/_compat.py", line 123, in iteritems
worker_1_a46c8ff2992b |     return iter(x.items())
worker_1_a46c8ff2992b | AttributeError: 'float' object has no attribute 'items'
```
Is this image the correct one?

**Comment by benjamingregory** [comment]
Hey @pedromachados -- 

Thanks for this issue. The Celery backend should work fine until Airflow 1.11 (both options currently resolve correctly) but we've gone ahead and updated it to what you suggested in the airflow.env file. We've also pinned the core and enterprise 1.10.1 examples to the `master-1.10.1` versions to avoid any future confusion.

Re: Redis, looking into it, the error you posted appears to be a Redis v3.0.0.post1 (https://github.com/celery/celery/issues/5175), which would be installed if you did `pip install celery[redis]`. If you're using our enterprise example, it should install Redis v4.0.10. We're unable to recreate the this issue posted using this version so I'm going to close this issue.

**Comment by benjamingregory** [comment]
Hey @pedromachados -- Thanks for submitting this issue.

We've done the following to address what you brought up:
1) Updated the Airflow Celery Backend reference (both should resolve fine for now but this sets us up to avoid any issue in Airflow 1.11). The warning shouldn't appear anymore. https://github.com/astronomer/astronomer/pull/165
2) Pined the Airflow Core and Enterprise examples to `ap-airflow:master-1.10.1` so it's clearer which image is being used in the future. https://github.com/astronomer/astronomer/pull/165
3) Capped the installed redis version to below 3.X to avoid the celery failure you noted - https://github.com/astronomer/astronomer/pull/168

Tested and confirmed that these solves the issues you brought up.

**Comment by pedromachados** [comment]
Great @benjamingregory I'll give it a try. Thanks for the quick response.
