### ISSUE TITLE
Stream container status to client

### ISSUE THREAD

**Issue by schnie** [astronomer/astronomer#178]
As a deployment.user, I want to see the status of my airflow cluster components in real time.
- Webserver
- Scheduler
- Workers

TODO:
~~- Commander subscribe to kubernetes watch api for namespace~~
~~- Houston subscribe to commander over gRPC~~
~~- Houston expose subscription to clients to listen for container status, querying with labels~~
~~- Clients query and/or subscribe and display container status~~

- Expose query/subscription to prometheus data, queried by release name
- Query / Subscribe in Orbit / CLI

**Comment by ryw** [comment]
@schnie this is done i'd say w/ @samblackk work on metrics tab, agree?

**Comment by schnie** [comment]
Yep, should be. I guess we're tracking it there so we can close this out.
