### ISSUE TITLE
Override environment variables on airflow deployments

### ISSUE THREAD

**Issue by schnie** [astronomer/astronomer#179]
We need the ability to override arbitrary deployment level airflow environment variables. Original issue here: https://github.com/astronomerio/astronomer/issues/146.

Helm is already set up to pass these environment variables through to every airflow container in the deployment.

We need to ensure that any environment variables that we're setting supersede anything that that a user inputs.

- [ ] Add support for passing environment variables in helm.
- [ ] Add support in API
- [x] Add support in Orbit
- [ ] Add support in CLI

**Comment by ryw** [comment]
@vparekh94 is this resolved now?

**Comment by schnie** [comment]
Yea, shipped this a while ago.
