### ISSUE TITLE
Add Platform Version to Settings page

### ISSUE THREAD

**Issue by benjamingregory** [astronomer/astronomer#184]
*Problem:*
When debugging with a customer, it is useful to know the platform version they have installed. This is not currently easily accessible and can cause delays when working with a customer team member who did not handle the install directly.

*Proposed Solution:* Make the installed version available in the UI under `Platform Settings` (possibly then extending to include some information on the K8s cluster it is running on, ip range, etc.). As an MVP, include in `Personal Settings` as a new tab called `Platform Version`.

**Comment by paolaperaza** [comment]
@ryw Just saw this in our queue. The Astronomer Platform version can currently be found within each deployment's Configure page in Orbit (but that's at a deployment level - for Enterprise folks there could be a mismatch if a single deployment isn't upgraded to their latest platform version). Out of curiosity, is that what this issue encompasses? Something listed in the SysAdmin view? Or something else?

![image](https://user-images.githubusercontent.com/31111752/63033820-3ffdbf00-be86-11e9-9180-925b450ac5ed.png)

**Comment by ryw** [comment]
Actually I just made a new issue for this https://github.com/astronomer/astronomer/issues/401 that is a simple solution, and I think this is important for all users because of cli mismatch issues. https://github.com/astronomer/astronomer/issues/401

So closing this one.
