### ISSUE TITLE
Send user events to metarouter.io by default

### ISSUE THREAD

**Issue by pcmaffey** [astronomer/astronomer#185]

**Comment by schnie** [comment]
@petedejoy we're already sending events aren't we?

**Comment by petedejoy** [comment]
Not as far as I can tell. Peter built this [analytics factory](https://github.com/astronomer/orbit-ui/blob/edfc090d8f09c98bd65fb7aa351766a7fbb07bc0/src/index.ejs#L40) that I believe has completely abstracted out all events we want to track, but nothing's implemented at the moment. I want to dive in and try to understand it at some point, but haven't had time yet.

**Comment by ryw** [comment]
@petedejoy is this done now?

**Comment by petedejoy** [comment]
PR isn't merged yet, but it's ready to roll.
