### ISSUE TITLE
False alert for alertname: TargetDown 

### ISSUE THREAD

**Issue by VickyWinner** [astronomer/astronomer#1880]
We are seeing this alert being thrown every day.  I opened a ticket and was told that its a false alert and will be taken care in next release.  Any update on this?
![image](https://github.com/astronomer/astronomer/assets/33285331/8914fa23-2220-4e3e-aae5-19cd2d695480)

**Comment by danielhoherd** [comment]
@VickyWinner This ticket doesn't have enough information for me to understand the problem well enough to be able to respond. If you have a paid support plan, please follow up with the support ticket you opened.

**Comment by wolfier** [comment]
The [Zendesk Ticket](https://astronomer.zendesk.com/agent/tickets/17071) should provide more information and @shubh-am-kumar was the support staff helping Vikas with this issue.

**Comment by danielhoherd** [comment]
I've created an internal engineering ticket to implement the changes needed to solve the problem using the fix described in the zendesk ticket. We can now confidently say that this will go out in the next release, 0.32.1.

**Comment by danielhoherd** [comment]
This fix has been merged and will be released with the next versions 0.30 and 0.32. 0.31 will not get the fix because it is EOL this month.
