### ISSUE TITLE
Backport Elasticsearch handler into 1.9 and 1.10.x images

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#216]

**Comment by ryw** [comment]
@rhwang10 have you started working on this yet?

**Comment by rhwang10** [comment]
Not officially, but I should have the working 1.9 image on my machine locally- just a matter of moving the ES handler into the 1.9-stable version, since airflow 1.9 didn't have the ES handler yet

**Comment by schnie** [comment]
Currently working on some follow up commits as we get closer to pushing this into production. Should be pretty close this week.

**Comment by schnie** [comment]
We're only releasing 0.8.0 with 1.10.2 support. Done here.
