### ISSUE TITLE
Direct integration w/ Okta

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#226]
Reference Auth0 integration:
https://github.com/astronomer/houston-api/blob/master/src/lib/oauth/providers/auth0/index.js

**Comment by schnie** [comment]
@petedejoy, we'll need to create a new `provider` here for `okta`. The new module will look similar to the `google` and `auth0` ones we have here: https://github.com/astronomer/houston-api/tree/master/src/lib/oauth/providers

**Comment by petedejoy** [comment]
This is just about finished up- still need to write tests, clean up a couple of things, and write a doc on how to set up the integration with your Okta server. I opened an issue for that here: https://github.com/astronomer/docs/issues/88

**Comment by petedejoy** [comment]
PRs are open on orbit and houston- everything should be good to go here!

**Comment by petedejoy** [comment]
Doc is finished up and live on https://preview.astronomer.io/docs/ee-integrating-auth-systems/

Will merge that to master as soon as my PR gets roped in.

**Comment by schnie** [comment]
All merged!

**Comment by petedejoy** [comment]
Sweet! Merging my doc into master so it's live. Should be viewable at https://www.astronomer.io/docs/ee-integrating-auth-systems/ shortly.
