### ISSUE TITLE
Job astronomer-kibana-default-index and astronomer-jetstream-job chart template doesn't allow scheduling constraints

### ISSUE THREAD

**Issue by VickyWinner** [astronomer/astronomer#2319]
### Issue

Job astronomer-jetstream-job chart template doesn't allow scheduling constraints
Astronomer: v0.34.1

### Resolution:
https://github.com/astronomer/astronomer/blob/master/charts/nats/templates/jetstream-job.yaml#L55 - nats chart might need to be updated.
https://github.com/astronomer/astronomer/blob/master/charts/kibana/templates/kibana-default-index-cronjob.yaml  might needs to be updated.

**Comment by pgvishnuram** [comment]
@VickyWinner this change is included in our new astronomer software  version 0.36.0.
