### ISSUE TITLE
Fix orbit caching issues

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#233]
After an upgrade or platform reinstall, orbit fails to load. The only way to get it back is to clear cache or use incognito.

**Comment by ryw** [comment]
Another customer:

```
Howdy all, I get a blank screen when I hit app.astro.xxx.io
Ah I think it has something to do with cookies.
Works in an incognito browser.
```

**Comment by schnie** [comment]
I think we just need to add some kind of hash to some filenames to cachebust or something along those lines.

**Comment by schnie** [comment]
@andriisoldatenko thinking this maybe caused by the `index.html` file being cached. Wondering if we could set some caching headers via nginx to help solve. Any other ideas?

https://github.com/astronomer/astronomer/blob/master/docker/platform/orbit-ui/include/nginx.conf

**Comment by andriisoldatenko** [comment]
fixed via https://github.com/astronomer/astronomer/pull/298
