### ISSUE TITLE
Fix browser redirect issue in Orbit

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#237]
Sometimes you can't click on your deployment from Orbit and get to an airflow deployment UI. It will redirect you back to the /deployments page on Orbit.

**Comment by ryw** [comment]
Can anyone reproduce this consistently?

**Comment by schnie** [comment]
Where was this originally seen?

**Comment by vparekh94** [comment]
Originally was a cloud issue - have not had any Enterprise customers report it since 0.8.2.

**Comment by schnie** [comment]
May have been fixed with new houston.

**Comment by vparekh94** [comment]
I say we close it until it's reported again on the new houston

**Comment by vparekh94** [comment]
I say we close it until someone reports it again on new houston.
