### ISSUE TITLE
Dollar amounts do not match AU usage on deployment config page with celery executor

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/astronomer#251]
**Describe the bug**
I looked at a few deployments I have access to and spun up a new one, and the default dollar amount listed is $250, not $170 - even though the AU's at "default" config levels effectively add up to 17 at a rate of $10 each.

The corresponding $ to default levels with _local_ executor is correct ($110), just not with Celery.

**To Reproduce**
1. Spin up a new deployment
2. Click on Workspace > Deployment > Configure > make sure Celery is selected (default)
3. Do not adjust any toggles
4. Scroll down to the bottom, where `Price` is listed in bold
5. You'll see $250, even though the AU's listed above add up to 17 (at a cost of $10 each)

The following default configs are listed:

Celery Executor: 1 Worker (10 AU)
Webserver (2 AU)
Scheduler (5 AU)

**Expected behavior**

The price listed at the bottom of the resource config page should correspond to the rate at which we effectively charge customers ($100 per 10 AU), and be updated dynamically on the UI for _all_ executors. 

**Desktop (please complete the following information):**
 - MacOS Mojave v10.14.2
 - Chrome

**Comment by paolaperaza** [comment]
Ah, I gotcha I gotcha - thanks @schnie. 

Is all of that CPU usage on Flower, Redis, etc. being "converted" to AU? I only ask because our pricing page charges per AU, and that total for the rest of the resource components isn't super clear in the way it corresponds to the dollar amount, if that makes sense

@petedejoy / @benjamingregory depending on what the actual minimum is for a standing deployment running with a Celery executor (related to [this](https://github.com/astronomer/astronomer/issues/252) issue), we might want to clarify on pricing page. The page right now implies that the starting price for local executor is $70, and $170 for Celery

**Comment by schnie** [comment]
@paolaperaza yep, all the underlying CPU/MEM of the components are rolled into the total AU.

**Comment by paolaperaza** [comment]
Closing this out as we've updated our pricing page to clarify the above, and @petedejoy shipped some new content on a [pricing section in our docs](https://www.astronomer.io/docs/pricing/).
