### ISSUE TITLE
Orbit doesn't detect value change when changing executor on a cluster

### ISSUE THREAD

**Issue by petedejoy** [astronomer/astronomer#261]
**Describe the bug**
When switching executor type of an existing deployment, the `Update` button in Orbit remains greyed out.

**To Reproduce**
1. Create a new deployment.
2. Head to deployment config.
3. Change executor
4. See greyed out `Update` button

**Expected behavior**
The `Update` button should be lit up and able to be pressed.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by petedejoy** [comment]
Ran into this same issue while building the RBAC form and have determined it's a bug in the `Select` component (src/instruments/forms/Select/index.js). It's not a massive issue, but here's what we have going on:

When submitting the form, I've confirmed that the following happens:
- The mutation runs successfully
- The snackbar comes up confirming the information was submitted
- The `Update` button gets greyed out initially
- The application state updates successfully and correctly
- If you click a different option before refreshing the app, the `Update` button reverts to acting as it did before the state change- it's disabled according to the "old" data. For example, if I change someone's role from `Admin` to `Editor` and submit the form, all looks good and the state changes, but if I then click `Admin` again, the button is disabled because the component isn't picking up the new state.

**Comment by ryw** [comment]
@petedejoy is this still an issue?

**Comment by petedejoy** [comment]
@ryw yes- it looks like you opened another issue for it today: https://github.com/astronomer/astronomer/issues/423

**Comment by petedejoy** [comment]
Hold up- looks like we changed the component so that the button just doesn't disable. Do you think that's a good solution for now? If so, we can close this out
