### ISSUE TITLE
CLI WISHLIST:

### ISSUE THREAD

**Issue by schnie** [astronomer/astronomer#263]
- Fix quirk when changing cluster, where workspace gets messed up
- Change UUID to ID everywhere.
- Make it easier to switch between things rather than copy/pasting ids

**Comment by vparekh94** [comment]
Deployments should show their names along with their release name when a user goes to push code.

right now:

```
virajparekh@orbiter:~/Code/Astronomer/airflow-example-dags$ astro de ls
 NAME     RELEASE NAME                 ASTRO      DEPLOYMENT ID                            
 Prod     mathematical-vacuum-6603     v0.7.5     66090c3e-1c71-460d-a09c-119e6ccf0974   
```

```
virajparekh@orbiter:~/Code/Astronomer/airflow-example-dags$ astro airflow deploy -f
Authenticated to demo.datarouter.ai 

Select which airflow deployment you want to deploy to:
 #    RELEASE NAME                  WORKSPACE                     DEPLOYMENT UUID                                   
 1    mathematical-vacuum-6603      viraj@astronomer.io's Workspace66090c3e-1c71-460d-a09c-119e6ccf0974              

```

The deployment NAME should be in descriptions of the environment when I go to deploy (so I don't have to remember that mathematical-vacuum is my prod instance).

**Comment by vparekh94** [comment]
There should be a command to describe a deployment, things like, Name, ID, Created At, config, etc.

something like 

`astro deployment info DEPLOYMENT_NAME`

**Comment by vparekh94** [comment]
astro deployment update should list possible flags:
```
virajparekh@orbiter:~$ astro de update
Error: must specify a deployment ID and at least one attribute to update.
Usage:
  astro deployment update [flags]

Aliases:
  update, up

Examples:

	astro deployment update UUID label=Production-Airflow

Flags:
  -h, --help   help for update

Global Flags:
      --workspace-id string   workspace assigned to deployment

````

**Comment by vparekh94** [comment]
`astro workspace stats` should list all deployments you have access to in a cluster, along with their config
