### ISSUE TITLE
Installing the CLI pulls the latest (alpha) version rather than the correct version for Cloud

### ISSUE THREAD

**Issue by petedejoy** [astronomer/astronomer#271]
**Describe the bug**
Installing our CLI via
```curl -sSL https://install.astronomer.io | sudo bash```
installs v0.8 of the CLI, which doesn't work with Cloud v0.7.5. For now, I'll update our getting started guide to include the version tag, but we should fix this at some point so that basic CLI install matches up with the version of Cloud that we're running.

**Comment by schnie** [comment]
@andriisoldatenko maybe you could take a look at this one? Maybe something we can do with godownloader/goreleaser? Or maybe we have to change the way we release things.

**Comment by andriisoldatenko** [comment]
fixed via https://github.com/astronomer/astro-cli/pull/200

**Comment by schnie** [comment]
Should be good to go. Hopefully the next alpha release won't show up. Can reopen if we need to.
