### ISSUE TITLE
RBAC UI requires NPM scripts to be run during our docker build

### ISSUE THREAD

**Issue by andrewhharmon** [astronomer/astronomer#279]
The new RBAC UI requires some NPM scripts to be run, otherwise it doesn't render correctly. 
The steps are outlined [here](https://github.com/apache/airflow/blob/v1-10-stable/CONTRIBUTING.md#npm-packages) for v1-10-stable. 

linking #244

**Comment by schnie** [comment]
@andrewhharmon @ashb is this only for development or do we need to add this to our production docker image for RBAC?

**Comment by ashb** [comment]
It's only needed if you are working on Airflow's built-in he/CSS. If you install Airflow from GitHub it's needed.

Npm isn't needed at runtime (dev nor prod)

**Comment by andrewhharmon** [comment]
Thanks Ash. Sorry for the confusion Greg.

**Comment by schnie** [comment]
@andrewhharmon so think we can close this? Sounds like we don't need it for production builds.

**Comment by ashb** [comment]
Our production builds install from a github fork don't they? We'd need it in that case.

**Comment by schnie** [comment]
Oh, I read that wrong. Yea we do install Airflow from a github tag. So does the version on pypi have everything built and packaged or something?

**Comment by ashb** [comment]
Yeah, we run `python ./setup.py compile_assets sdist` so the built .tar.gz has compiled assets in it.

**Comment by schnie** [comment]
This is done, added like 35MB after removing all build requirements.
