### ISSUE TITLE
Airflow version on Astronomer UI does not match my running Airflow version

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/astronomer#286]
**Describe the bug**
In the configure page of an existing deployment on app.astronomer.cloud, I see an Airflow version as part of my deployment description that does _not_ dynamically update according to the Airflow version I'm actually running.

Looks like it might be fixed to Airflow v1.9, but we have more than a handful of customers running 1.10, or 1.10.1, etc.

**To Reproduce**
1. Log into an existing deployment on app.astronomer.cloud
2. Navigate to the `Configure` page
3. The Airflow version listed under the deployment description may or may not match your current Airflow version

**Expected behavior**
The Airflow Version of my deployment should always match the Airflow version I'm currently running.

**Screenshots**

Astronomer UI - 
![Deployment Configure Page](https://user-images.githubusercontent.com/31111752/55422637-15037600-554a-11e9-8db7-850dafea41c3.png)

Airflow UI - 
![image](https://user-images.githubusercontent.com/31111752/55422715-45e3ab00-554a-11e9-91b3-0ec5b93edd15.png)

**Comment by schnie** [comment]
Yep, this needs to be fixed. The version in orbit is hard-coded because we originally only had 1.9, then folks started pushing up our 1.10 image before we had a chance to fully build the feature. 

Full feature is being tracked here: https://github.com/astronomer/astronomer/issues/259

**Comment by paolaperaza** [comment]
Ah, got it @schnie - hadn't seen that issue! Sweet. Want me to keep this one up since it's more detailed from what a user might see, or consolidate?

**Comment by schnie** [comment]
@paolaperaza yea sure. I'll add this to the platform project board so we can track them together.

**Comment by petedejoy** [comment]
Self-assigning this one- after talking with @schnie, I'm just going to comment out the bit in Orbit that shows the airflow version being used. That information currently isn't easily-accessible by Orbit since it lives in our customers' Dockerfiles. For now, no information is better than wrong information.

**Comment by petedejoy** [comment]
Fixed with 82bcbae33c86be002f2418ecbe046eab2e92953c

**Comment by petedejoy** [comment]
Accomplished with https://github.com/astronomer/orbit-ui/commit/82bcbae33c86be002f2418ecbe046eab2e92953c
