### ISSUE TITLE
New system component: Necropolis 

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#287]
Garbage collector for Astronomer platform

[Name inspiration](https://www.space.com/36602-space-junk-cleanup-concepts.html)

In order to maintain a tidy system, the Astronomer platform should be self-cleaning by default.

- [ ] Databases for deleted deployments
- [ ] Old Docker images
- [ ] More stuff (please edit/add to this list)!

**Comment by schnie** [comment]
Dupe of https://github.com/astronomer/astronomer/issues/272. 

Copied name link over to the original issue. Closing this one.

**Comment by ryw** [comment]
Ah i searched - didn't see it :)
