### ISSUE TITLE
Add `Identify` Analytics.js tracking to the application

### ISSUE THREAD

**Issue by petedejoy** [astronomer/astronomer#288]
**Is your feature request related to a problem? Please describe.**
We need to associate users with their `userId` upon signup so that we can see _who_ is performing actions in the app. For example, we'd like to see when customer x creates a new airflow deployment. We'd also like to see when new user x signs up, especially since we'll be opening the app signup to the public once billing is finished.

**Describe the solution you'd like**
Identify call fires upon signup via local u/pw, google auth, or github auth. We see that event in our cloud-events slack channel.

**Additional context**
Peter's tracking factory is fully built out in orbit, so it should just take adding identify methods to the signup/creat user mutations in Orbit.

**Comment by benjamingregory** [comment]
https://github.com/astronomer/orbit-ui/pull/68
https://github.com/astronomer/houston-api/pull/43
