### ISSUE TITLE
Update Airflow image to 1.10.3

### ISSUE THREAD

**Issue by schnie** [astronomer/astronomer#296]
Airflow 1.10.3 has been released and includes a fix for the `KubernetesExecutor` `ResourceQuota` issue.

We should release this feature with our next platform release. For a working image, we'll need to update our `v1-10-stable` branch to include `1.10.3` from apache and layer on our:

- [x] Theme
- [x] Elasticsearch Logging PR
- [x] Kube labels PR

**Comment by andriisoldatenko** [comment]
@schnie please review.
https://github.com/astronomer/airflow/commits/v1-10-3

**Comment by andriisoldatenko** [comment]
also please review PR https://github.com/astronomer/astronomer/pull/297/files

**Comment by schnie** [comment]
Just cut official 1.10.3-1 release and pointed production image toward it. Done here!
