### ISSUE TITLE
Include Total AU Count in Deployment "Configure" Page

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/astronomer#301]
**Pain Point**

Currently, Astronomer Users using either the Celery or Local Executor are only able to configure the AUs associated with Webserver + Scheduler + Workers, but the AU's needed for Redis + Flower + StatsD + Pgbouncer (fixed) are not clear in how they contribute to total resources cost.

Total AU count for your deployment is not explicitly stated anywhere.

A customer might think that default resource Celery only costs 17 AU, not 25 AU. Those additional components show up in the spectrum at the bottom, but they're reflected in CPU units, not AUs which is misleading.

**Potential Solution**
The total dollar amount is correctly rendered at the bottom, but we should make the AUs required for ALL components clearer, and the total AU count next to or near the total dollar amount.

![image](https://user-images.githubusercontent.com/31111752/57156674-871ae500-6dac-11e9-98c7-d9a0aef0eb1f.png)

An MVP solution could be two things:
1. Add AU count to all components in the colored spectrum, in addition to CPU + Memory
2. Add "Total AU" count under the existing dollar amount at the bottom of the page.

**Considered Alternatives**
This may or may not change if we implement the request in #266 (Scale up CPU and Memory Individually).

**Comment by paolaperaza** [comment]
@samblackk I know you're in the wake of many other front-end bug fixes and features, but adding you to this issue just so you have it on your radar!

**Comment by samblackk** [comment]
Closing this - feature updated in https://github.com/astronomer/orbit-ui/pull/108
