### ISSUE TITLE
SysAdmin: View + Delete Deployments

### ISSUE THREAD

**Issue by petedejoy** [astronomer/astronomer#316]
As a System Admin, I want to be able to view all Airflow deployments and optionally delete them.

**Comment by ryw** [comment]
just edited (simplified) this issue, @petedejoy.

**Comment by ryw** [comment]
Houston PR: https://github.com/astronomer/houston-api/pull/88

**Comment by schnie** [comment]
@samblackk we'll need the `/admin` route up and running for this one. Somewhere to list all deployments in the system and delete.

**Comment by petedejoy** [comment]
@schnie I'm thinking we can close this out without the front-end counterpart fully built out. That can come later- for 0.10 all we need is the ability to run the mutation from the playground.

**Comment by schnie** [comment]
@ryw work for you?

**Comment by ryw** [comment]
If @petedejoy and @paolaperaza are happy with this for now, let's keep the issue open (since it's not fully done), but put it into v1.0.

**Comment by paolaperaza** [comment]
Noted and agreed here, @ryw ! If the mutation is out there and works I'm good for now.

Agreed on keeping this open if we do want to throw a front-end on top of it, or perhaps closing this and creating another issue for that piece with a rescope. I'll defer to you all since you're working on it, but thanks @petedejoy / @samblackk.

**Comment by samblackk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SysAdmin: View + Delete Deployments](https://trello.com/c/21QAubXl/10-sysadmin-view-delete-deployments)

**Comment by ryw** [comment]
@schnie are we planning on putting this in v0.10.1? Update milestone if so...

**Comment by schnie** [comment]
Yea I think we're close on it

**Comment by schnie** [comment]
All merged!
