### ISSUE TITLE
SysAdmin: Invite user

### ISSUE THREAD

**Issue by petedejoy** [astronomer/astronomer#317]
As a SysAdmin, I want to be able to invite a user to an Astronomer cluster (i.e. sign them up).

**Comment by ashb** [comment]
@samblackk I'll start working on the houston mutations for this (which are relativity easy) but we might want to think about how we expose this sysadmin-level functionality to the UI - this is the first admin-only feature we'll have.

**Comment by schnie** [comment]
I think we started a platform dashboard a while back. It doesn't look like much, but it's a little bit of a start. https://github.com/astronomer/orbit-ui/tree/master/src/modules/platform

**Comment by ryw** [comment]
I’m thinking it’s a good feature to blaze a trail for admin UI since it’s so simple, and will force us to think through nav

**Comment by petedejoy** [comment]
Got it. So when you get invited to an Astronomer cluster, does that auto-build a workspace for you? Or will you just be presented with a screen to create a workspace?

**Comment by ryw** [comment]
You will manually create your first workspace

**Comment by schnie** [comment]
Orbit and Houston PRs are merged!
