### ISSUE TITLE
Cloud Trial ($150 Credit, 14-Days)

### ISSUE THREAD

**Issue by petedejoy** [astronomer/astronomer#318]
Allow users to freely use Astronomer Cloud until they've reached $150 in AU, or 14 days, whichever is shorter. After $110 in credits used, or 10 days, they should get an email, and an in-app banner that they need to provide credit card to continue usage of the platform. They have 72 hours to provide credit card, otherwise we will disable their account and delete their deployment.

Once their credit card is entered and verified, they can create additional workspaces. New workspaces must have credit card added immediately.

**Comment by ryw** [comment]
@petedejoy break this into two issues

**Comment by petedejoy** [comment]
Expanding on this a bit, we'd only allow full Cloud usage in the absence of payment information _if_ the workspace was created from the "Start a Trail" form we're talking about building. If a user creates a new workspace from the UI, they should be blocked immediately until the workspace has an associated credit card. This will ensure that users can't get multiple workspaces of free credit-based trials.

**Comment by petedejoy** [comment]
This is closely related to https://github.com/astronomer/astronomer/issues/319- I posted an outline in that issue of how we'll accomplish this in the short term.

**Comment by petedejoy** [comment]
Working on limiting to 1 trial/user now. After chatting with @schnie, here's where we landed:

- [ ] Add a `trialEndDate` field to the User table in the datamodel
- [ ] Add a `userCapabilities` type with an `isTrialing` bool
- [ ] Add `userCapabilities` to the `User` type
- [ ] Add mutation to set trial end date in case SysAdmins need to extend trials
- [ ] Set `isTrialing` bool based on whether or not `Date.now()` is between `createdAt` and `trialEndDate`

**Comment by petedejoy** [comment]
Ported this ^ subproject over to a new issue here: https://github.com/astronomer/astronomer/issues/338

**Comment by petedejoy** [comment]
Closed by https://github.com/astronomer/houston-api/pull/71
