### ISSUE TITLE
Orbit: Email invite field does not render uppercase letters

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/astronomer#326]
**Describe the bug**
When an existing user invites another to a workspace, the email address field does not permit uppercase letters.

I'm not thrown an error if attempted, but the letter automatically renders as a lowercase instead.

**Customer Behavior/Impact**

- User #1 authenticated to Astronomer Cloud via GitHub with an email address with a capital R
- The "User Invite" email address field in Orbit won't let you pass an uppercase letter, so
- User #2 can't invite and confirm the correct email address for User #1 in his shared workspace

**Expected behavior**
The email input field should properly render uppercase letters and our API should properly receive those values.

![image](https://user-images.githubusercontent.com/31111752/58721760-b3258800-83a3-11e9-8e84-9b1c4c57e49e.png)

**Comment by schnie** [comment]
Closed via https://github.com/astronomer/orbit-ui/pull/85

**Comment by paolaperaza** [comment]
@samblackk Hm, now I've got a case or two where a user is sent an invite to an email address with 1 or more uppercase letters, and 2 separate records are created in the DB if an invite is sent to that same email address but in all lower-case. Typically, the one with the uppercase letter is given by an Auth Provider (as in the example with GitHub auth above) and isn't modifiable.

Should we/can we consolidate those 2 users?

![image (7)](https://user-images.githubusercontent.com/31111752/61903169-e98a0a00-aef1-11e9-8657-55fff88c4829.png)

**Comment by samblackk** [comment]
I think this is something that needs updating at the API layer - check for the email address w/o case sensitivity. Looking into it.

**Comment by paolaperaza** [comment]
Sweet, thanks @samblackk !

**Comment by samblackk** [comment]
PR opened to resolve email checking at the API layer.

**Comment by paolaperaza** [comment]
@samblackk Saw your PR was merged! This close-able?

**Comment by samblackk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Orbit: Email invite field does not render uppercase letters](https://trello.com/c/rOnjUZjA/9-orbit-email-invite-field-does-not-render-uppercase-letters)

**Comment by petedejoy** [comment]
Hey @samblackk / @schnie! @vparekh94 and I just ran into this issue with a customer. They kept getting ```InviteTokenEmailError: This email is not associated with the specified invite token```

I believe this is because their ActiveDirectory enforces their email have capitalization (ie. PDejoy@Astronomer.io), so when they signed up with Okta they ran into some weird issues. Was this not included in 0.10? 

If it _wasn't_ included, then I believe this is the fix they need. If it _was_, I'll need to think a bit more on this one.

**Comment by schnie** [comment]
Yep! Will be in v0.10.1
