### ISSUE TITLE
Cannot type numbers into slider fields

### ISSUE THREAD

**Issue by vparekh94** [astronomer/astronomer#329]
**Describe the bug**
If you go to type a number into any of the AU values instead of using the slider, the page breaks

**To Reproduce**
1. Go to 'Configure'
2. Type any number into the slider
3. Hit update
4. 

**Expected behavior**
We should ether warn users that they need to use the slider, or verify the input after they type something in.

**Screenshots**
![image](https://user-images.githubusercontent.com/19679395/58904029-b9ce3b00-86d4-11e9-8842-e9b064548c1c.png)

**Additional context**
This was bought up by a customer recently running 0.9.1-alpha.1

**Comment by schnie** [comment]
Closed via https://github.com/astronomer/orbit-ui/pull/85
