### ISSUE TITLE
Orbit: "Pending" user can't be deleted from Workspace by Admin

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/astronomer#337]
**Describe the bug**
If I invite a user to my Workspace and for any reason want to rescind their invite or delete the "Pending" user, I can't in Orbit.

"Delete" button is greyed out - even as an Admin.

**To Reproduce**
1. Invite a new user to your Workspace
2. Before they accept the invitation or are otherwise marked as "Joined" in the Workspace, go to `Users` > `User` > `Configure Access` > `Cancel Invitation`
3. See greyed out button

**Expected behavior**
Admins should be able to cancel an invitation or delete a user from their Workspace even if they have not yet accepted. 

**Screenshots**

![image](https://user-images.githubusercontent.com/31111752/59532428-b5650780-8eb6-11e9-9bc9-5ef432590269.png)

**Additional context**

A customer reported this in v0.9 on 6/14 and I was able to replicate the behavior on datarouter.ai.

**Comment by petedejoy** [comment]
@samblackk - if it's cool with you, I'll take this one. I built these components and have a good idea of how to get this patched up.

**Comment by schnie** [comment]
This is merged. Will update on DR soon
