### ISSUE TITLE
Limit Trial Workspace Functionality

### ISSUE THREAD

**Issue by petedejoy** [astronomer/astronomer#338]
Working on limiting to 1 trial per user so that, once suspended, users cannot get second trials by creating a new workspace. Here's the scope of this project:

- [x] Add a `trialEndDate` field to the User table in the datamodel
- [x] Add a `userCapabilities` type with an `isTrialing` bool to the application schema
- [x] Add `userCapabilities` to the `User` type in the schema
- [x] Add mutation to change `trialEndDate` in case SysAdmins need to extend trials
- [x] Set `isTrialing` bool based on whether or not `Date.now()` is between `createdAt` and `trialEndDate`
- [x] Block `createWorkspace` based on whether or not `isTrialing` is truthy

**Comment by petedejoy** [comment]
Update here: after discussing with @schnie we're thinking it'll be better to actually *not* limit action at the user level, as it gets messy quickly and ends up giving way to a bad UX. 

Rather, we're thinking that it'll be better to limit action that a user is allowed to perform during their trial. We'd like to add the `isTrialing` bool to the `Workspace` type and then only allow one deployment with default (greyed out) configs if that bool is true. The prospect can access our app's full functionality by adding a payment method. @ryw - what do you think about that?

**Comment by ryw** [comment]
I'm down to go with what you guys discussed

**Comment by petedejoy** [comment]
Great. I have a working branch here: https://github.com/astronomer/houston-api/tree/feature/trial-workspace

**Comment by petedejoy** [comment]
Closed by https://github.com/astronomer/houston-api/pull/71
