### ISSUE TITLE
Metrics Enhancements

### ISSUE THREAD

**Issue by samblackk** [astronomer/astronomer#339]
Prometheus Metrics Enhancements (for v0.10): 
- [x] Reorder/combine metric containers
- [x] Lazyload / singleton load data from Prometheus @samblackk 
- [x] "Subscribe" selector to show/hide metric panels on the Deployment Overview page. @samblackk 
- [ ] CLI update: `astro status` (more info tbd)
- [x] Show 0's (or something) instead of NaN's on quota gauges
- [x] Sort Container Status List (A-Z, timestamp)

**Comment by samblackk** [comment]
Houston Update Re: Prom Queries
- Update schema to accept an `enum` list of keys 
- Group queries by common data - `deployment stats`, `task status` etc.

**Comment by ryw** [comment]
Just tested this on datarouter, works great - closing :)
