### ISSUE TITLE
The `clean-airflow-logs` script is added to /etc/periodic/15min but /usr/sbin/crond is never started

### ISSUE THREAD

**Issue by rgarver** [astronomer/astronomer#344]
**Describe the bug**
In the `astronomerinc/ap-airflow:master-1.10.3` Dockerfile the `clean-airflow-logs` script is added to the /etc/periodic/15min directory with the expectation that it will get run periodically. Since tini doesn't do any daemon management and the entrypoint script doesn't handle this, crond is never started therefore the script never runs.

**Expected behavior**
The script should run every 15 minutes

**Comment by schnie** [comment]
Hey @rgarver we run everything on kubernetes and have the `crond` script starting as a sidecar to the actual airflow processes. Here's an example on the celery workers: https://github.com/astronomer/helm.astronomer.io/blob/master/charts/airflow/templates/workers/worker-deployment.yaml#L81-L92

**Comment by rgarver** [comment]
Ah! makes sense thank you.
