### ISSUE TITLE
Clarify which docker images are compatible/ safe to use

### ISSUE THREAD

**Issue by andrewhharmon** [astronomer/astronomer#358]
Users go to docker hub and see lot's of tags and aren't sure which ones to use. we had a user have an issue bc they used master which had a known bug. We could add an overview page to docker hub. 

Additionally, we should specify which versions are ok to use in cloud.

**Comment by schnie** [comment]
Yep, we should make some nice looking docker hub pages describing the naming convention, possibly dress up with some images as well. Postgres, redis and others have docs worth replicating.

**Comment by andrewhharmon** [comment]
fwiw, i've been guiding cloud customers to uses `0.9.3-1.10.3-onbuild`

**Comment by paolaperaza** [comment]
+1 here - We're seeing a lot of customers come in with incompatibilities across images, CLI versions, Astro versions, Airflow versions, packages, etc. Even if those incompatibilities exist we should have some guidelines written to help people navigate those options, either in dockerhub or somewhere in our docs directly.

@schnie Is this something @andrewhharmon and I could tackle? Do you envision more of an initial effort in Dockerhub directly or in our own docs?

**Comment by schnie** [comment]
Yes, absolutely! I think we should just come up with a little markdown page that looks similar to the postgres or redis dockerhub pages eg: https://hub.docker.com/_/redis.

Something to describe our tagging system, then maybe a nice image and usage docs or something. We can start with just the airflow one, but can replicate to other repos if we want.
