### ISSUE TITLE
No Host error in airflow logs

### ISSUE THREAD

**Issue by andrewhharmon** [astronomer/astronomer#363]
**Describe the bug**
We are having customer's tasks fail and when they look at the logs, they can't be retrieved. Instead the get an error "No host". The logs do in fact exist on the worker pod. Most of the time we've seen these logs abruptly stop so they aren't helpful indicating the task hard crashed. We have since seen one of these tasks on retry throw a -11 error which i believe is out of memory. My theory is the AU is too low and their tasks are crashing the airflow worker. I'm not sure what happens to other tasks executing on the same pod. Guessing maybe they just hard crash with out the -11 code. 

**To Reproduce**
not easily reporoducable

**Expected behavior**
Some clearer messaging/logging when a pod is under memory/cpu pressure or crashes

**Additional context**
I opened a Jira for this, but since then @ashb thinks it may not actually be an Airflow bug. Linking here just for additional context. https://issues.apache.org/jira/browse/AIRFLOW-4922?filter=-2

**Comment by ashb** [comment]
I still think it's an Airflow bug, just not in the place I thought at first.

**Comment by ryw** [comment]
Closing issue here, let's use Airflow Jira to track this, and if we can isolate it to an Astronomer problem we can open new issue here
