### ISSUE TITLE
Set role for Service Accounts

### ISSUE THREAD

**Issue by schnie** [astronomer/astronomer#364]
Right now we are defaulting service account creation to use a single role and don't let users modify it. Users are running into situations where our default role is not privileged enough to do certain things like delete deployments.

We are already letting users choose the role for new users so we should be able to re-use a few things and drop this ability into service accounts.

**Comment by schnie** [comment]
@samblackk, I think @petedejoy ran into a few issues with our Role Switcher component that we ripped from the Executor Switcher. We may want to patch that up if we can, while we're in here.

Also might be a good time to change the icons, or change that component up all together. cc @Inkdryer

**Comment by schnie** [comment]
@samblackk think we could get this one knocked out next?

**Comment by samblackk** [comment]
@schnie Yes! PR coming today.

**Comment by ryw** [comment]
@samblackk did you re-open this intentionally?

**Comment by samblackk** [comment]
@ryw Yes - the primary issue in this ticket isn't addressed - I fixed the secondary issue of the role selector state. Working on adding the role selector to the service account config right now, which will close this issue when merged.

**Comment by samblackk** [comment]
@schnie Is this good to go?

**Comment by schnie** [comment]
Think we're good here!
