### ISSUE TITLE
After entering credit card, banner still shows w/ 0 days

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#370]
<img width="531" alt="Screen Shot 2019-07-17 at 11 06 52 AM" src="https://user-images.githubusercontent.com/4283/61386906-19e30000-a883-11e9-83bb-ec301dcb97dc.png">

**Comment by petedejoy** [comment]
Thanks for finding this @ryw. Commenting as a reminder to fix the padding on the button with this PR.
