### ISSUE TITLE
30 min task stream, until 30 min data gets filled up, success data flips between each refresh

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#376]
![2019-07-18 21 54 52](https://user-images.githubusercontent.com/4283/61503738-ded9ed00-a9a6-11e9-9e6a-587bc1b82ee5.gif)

Maybe related to https://github.com/astronomer/orbit-ui/blob/5d02aef05645f30069755f36aba464a78d9fee6b/src/modules/metrics/DeploymentMetrics/index.js#L64 - does default view know it's 30 min? Something is strange w/ only 30 min view, and because it's default view maybe that's a clue :(

**Comment by ryw** [comment]
@samblackk do you want to take a crack at this or want me to?

**Comment by samblackk** [comment]
@ryw I'm getting a PR for this opening today.
