### ISSUE TITLE
Automated Registry Cleaning

### ISSUE THREAD

**Issue by vparekh94** [astronomer/astronomer#380]
We should have an easy or built in way to clean up old deployment tags from the registry for EE environments that are not backed by cloud storage buckets.

This could be a cron script that can be configured to run periodically that deletes every X tags (similar to what @andriisoldatenko has done for Cloud).

**Comment by vparekh94** [comment]
@ianstanton how would you configure it to use the local file system to back it up?

**Comment by schnie** [comment]
@vparekh94 this might be a dupe of https://github.com/astronomer/astronomer/issues/272, unless you are thinking of this as a more ad-hoc script until we have it fully built in to the platform.

The other option here is to expand the registry volume, but I'd be surprised if any enterprise customers are hitting the default limits, are there?

This works like a charm and I've successfully done it multiple times now - https://stackoverflow.com/questions/40335179/can-a-persistent-volume-be-resized

**Comment by andriisoldatenko** [comment]
@vparekh94 just FYI https://github.com/astronomer/registry-cleanup/

**Comment by vparekh94** [comment]
@schnie partial a duplicate of #272 for sure - did not see that one. Yeah, I think the customer just wants some guidance on making sure the registry doesn't overflow.

@andriisoldatenko thanks for that - did knot know it existed :smile: 

With the alerts, andrii's script, and that issue, I think we can close this.
