### ISSUE TITLE
Cannot filter dags on web UI 1.10.3

### ISSUE THREAD

**Issue by dstandish** [astronomer/astronomer#387]
On web UI, you can search for a single dag.  But you cannot filter to a subset of dags by searching for a substring.  Nor it seems can you filter by owner etc.

Apparently this is fixed in RBAC UI in 1.10.4. I know that when 1.10.4 comes out, astronomer will get it.  

In any case the bug is present in 1.10.3 so creating issue in case you want to do anything about it.

**Comment by ryw** [comment]
Thanks @dstandish
