### ISSUE TITLE
Sync Connections and Variables across Deployments

### ISSUE THREAD

**Issue by vparekh94** [astronomer/astronomer#388]
As a user, I'd love the ability to sync connections and variables across deployments. This would make it easy to start using new environments after they are spun up as users wouldn't need to manually insert connections or have a DAG that syncs connections.

Some sort of "Sync Connections" button that shows all the other environments and allows a system admin to pick which connections they want to import into an environment would be great.

Any other sort of solution that allows for users to automate the connections and variables without needing to copy and paste credentials would fit the use case

**Comment by ryw** [comment]
Dupe w/ #174

**Comment by paolaperaza** [comment]
@ryw @vparekh94 Was just going in to comment on #174 when I saw this. (Keep this one, delete the other?)

Either way, very hard +1 here - we should bump this up the queue if possible. I'm personally asked about it at least once a day, every day, by a different customer.

**Comment by vparekh94** [comment]
#174 is a lot more thought out, closing this in favor of it.
