### ISSUE TITLE
KubernetesExecutor Deployments start w/ 10AU extra space

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#389]
* [x] Orbit - Show 10AU  extra space cost in price estimate for new KubeExecutor deployment
* [x] Houston - Set 10AU extra space  for new KubeExecutor deployment

**Comment by schnie** [comment]
Think we're done here!

**Comment by schnie** [comment]
@samblackk @petedejoy looks like something is going on with the extra au slider on datarouter. It's not rendering and seems to get stuck.

**Comment by samblackk** [comment]
I'm unable to replicate this @schnie.

**Comment by petedejoy** [comment]
I can't replicate slider issues, but I do get the following message from my browser when I try to update my deployment extra AU and save: 
![image](https://user-images.githubusercontent.com/32076749/62871065-bb296e80-bce8-11e9-8aee-302dae84366e.png)

**Comment by petedejoy** [comment]
(I'll open up a separate issue for ^)

**Comment by ryw** [comment]
I can't replicate either - closing this for now.
