### ISSUE TITLE
Show current Astronomer Platform version in the user dropdown menu

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#401]
Small font at bottom of menu "Astronomer v0.10.8-alpha.4"

**Comment by schnie** [comment]
@samblackk seems like we could add a new houston query `version`, or something to return the current version which will be passed into the houston configuration via helm, available with `config.get('helm.releaseVersion'`.

**Comment by samblackk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show current Astronomer Platform version in the user dropdown menu](https://trello.com/c/vaJkDXgU/4-show-current-astronomer-platform-version-in-the-user-dropdown-menu)
