### ISSUE TITLE
Current settings for Extra AU getting wiped when change webserver/scheduler AU

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#402]
On staging.astronomer.io

1. Set Extra AU to 10, Save - confirm that it's at 10. All good.
2. Change webserver AU, save - go back to config, Extra AU has been set to 0.

**Comment by petedejoy** [comment]
Does this happen for all executor types?

**Comment by ryw** [comment]
I only tested K8s

**Comment by ryw** [comment]
@petedejoy are you working on this today? Might be last issue for 0.10

**Comment by petedejoy** [comment]
Yes. Just fixed it- I’ll send up a PR shortly.

**Comment by schnie** [comment]
Fixed with the `updateDeployment` most recent patch. Going out with v0.9.7, v0.10.0.

**Comment by petedejoy** [comment]
Adding some color here- this was broken by the initial `fix/email-alerts` changes that caused the resolver to only run with updated payload args. We should work to move the `extraAu` field off of the json `payload` field and onto the standard deployment `config` field- it's currently on `payload.properties` and that doesn't make a ton of sense.

**Comment by ryw** [comment]
Can you drop issue in for this refactoring @petedejoy
