### ISSUE TITLE
Upgrade Airflow to 1.10.4

### ISSUE THREAD

**Issue by schnie** [astronomer/astronomer#403]

**Comment by ryw** [comment]
@schnie does https://github.com/astronomer/astronomer/commit/22111f0bd112acdab9fd92a34b3f1cf541136478close this?

**Comment by schnie** [comment]
We're pointing at the branch, we still need to cut the release once we confirm it works. Purposely leaving open until we flip over.

**Comment by andriisoldatenko** [comment]
@ryw FYI https://github.com/astronomer/airflow/tree/v1-10-4

**Comment by andriisoldatenko** [comment]
@ryw @schnie this one done
https://github.com/astronomer/airflow/tree/v1-10-4
https://github.com/astronomer/astronomer/blob/master/docker/airflow/1.10.4/Dockerfile#L27
