### ISSUE TITLE
Can change local dev bind mounts using astro config

### ISSUE THREAD

**Issue by dstandish** [astronomer/astronomer#407]
**Problem**
I want more flexibility in project structure.  E.g.:
* don't want `include` folder
* don't want dags folder in project root
* don't want plugins folder in project root

**Proposed solution**
I'd like it if we could change bind mounts in the astro config file.

**Alternatives considered**
Could use custom docker-compose file but then we can't use astro airflow start.

**Comment by paolaperaza** [comment]
@schnie I'm cleaning out the last of the issues in this repo - this relevant to transfer over and/or merge with any other existing issues that you know of?

(cc: @dstandish we're privatizing this GitHub repo whilst working on ways to still allow public trackable feature requests. Appreciate you posting in here back in August - not letting it get lost in the mix 😊)

**Comment by dstandish** [comment]
hey @paolaperaza 

Thanks for the note.

FWIW, since creating this ticket, I restructured my repo to be compatible with astro cli.  So this feature is not presently something I am particularly concerned with.
