### ISSUE TITLE
Metrics tab error

### ISSUE THREAD

**Issue by schnie** [astronomer/astronomer#412]
Flipping to the metrics tab of a new deployment on 0.10.0-rc.2 (on datarouter.ai), shows a DAG Gone it error. Houston _seems_ ok, so may be client side.

**Comment by samblackk** [comment]
@schnie I can't replicate this either. Metrics tab is rendering fine with a new deployment for me on datarouter.

**Comment by petedejoy** [comment]
I also am having trouble reproducing this- not seein' anything weird in houston or orbit.

**Comment by ashb** [comment]
Thirded. Closing this one.
