### ISSUE TITLE
Browser throws unsaved changes message when updating a deployment config

### ISSUE THREAD

**Issue by petedejoy** [astronomer/astronomer#414]
It seems that Chrome throws the following message when you try to change a deployment config and click the `Update` button on the form. It seems that the message also gets thrown when clicking out of the `Configure` tab, even if nothing on the deployment has been changed: 
![image](https://user-images.githubusercontent.com/32076749/62871458-87027d80-bce9-11e9-9369-35d31a2a7970.png)

**Comment by ryw** [comment]
@petedejoy can you come up with steps to replicate this consistently?

**Comment by petedejoy** [comment]
Yes. On Datarouter:
1. Create new Airflow deployment
2. Click into `Configure` tab on that deployment
3. Click back to `Overview` tab and the message gets thrown

Alternatively,

1. Tweak any slider on `Configure` tab
2. Click `Update` button and message gets thrown before saving

This is on Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by ryw** [comment]
I still see this issue for both `configure` and `alerts` tabs on 0.10.0-rc.6 :(

**Comment by ryw** [comment]
Confirmed fixed on DR :)
