### ISSUE TITLE
Clear cache every time page load

### ISSUE THREAD

**Issue by vparekh94** [astronomer/astronomer#415]
Cache can cause some funny behavior in Astronomer - especially after going through an upgrade. It would be nice if every time the page loaded, it clears out the corresponding cache. 

Bit out of my knowledge base with this one, so I'll let @petedejoy and @ryw add more about how it should work.

**Comment by petedejoy** [comment]
@vparekh94 is this just related to auth tokens? I know we've had an issue before where the auth token in the browser at /token is saved in the browser's localStorage and causes auth errors.

**Comment by vparekh94** [comment]
I've only seen it happen with the auth token - I believe we fixed the other caching issues with 0.9.7

**Comment by petedejoy** [comment]
Sweet- I'll have a hotfix for you today!

**Comment by petedejoy** [comment]
All done here!
