### ISSUE TITLE
Resources bar - Extra space not filling graph

### ISSUE THREAD

**Issue by samblackk** [astronomer/astronomer#419]
<img width="493" alt="screen_shot_2019-08-14_at_9 07 31_am" src="https://user-images.githubusercontent.com/6862485/63025880-2190c700-be78-11e9-99a7-3b5bfc10c2c9.png">

White bar should span the extra whitespace to the right.

**Comment by samblackk** [comment]
Hotfix: https://github.com/astronomer/orbit-ui/commit/a1099fb8928b08f1efeacdfda9d226309f59693a

**Comment by ashb** [comment]
LGTM

**Comment by ryw** [comment]
Hmm not fixed on DR - we sure platform is upgraded to latest? Which is why I added https://github.com/astronomer/astronomer/issues/401 :)

**Comment by ryw** [comment]
Confirmed working on DR :)
