### ISSUE TITLE
Data flipping 30 minutes bug is still present

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#420]
![2019-08-14 09 47 55](https://user-images.githubusercontent.com/4283/63026196-ba274700-be78-11e9-8e33-164d1a7a84f4.gif)

**Comment by ryw** [comment]
Failure data flips too
![2019-08-14 09 47 55](https://user-images.githubusercontent.com/4283/63026877-ee4f3780-be79-11e9-92ac-7456102a77b9.gif)

**Comment by samblackk** [comment]
Would you be open to visiting a different chart for this information?

**Comment by ryw** [comment]
I think we should just fix it where it is - I can look at it again if you'd like.

**Comment by samblackk** [comment]
This is next up on my list.

**Comment by samblackk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data flipping 30 minutes bug is still present](https://trello.com/c/DAWPSIIo/3-data-flipping-30-minutes-bug-is-still-present)

**Comment by schnie** [comment]
@samblackk we're trying to ship v0.10.1 ASAP to put on new cloud. Do you think we can squeeze this in or should we push it out to v0.10.2?

**Comment by samblackk** [comment]
@schnie push to v0.10.2 - I'm still working through finding the root cause of this - it doesn't happen all the time while I'm testing.

**Comment by schnie** [comment]
@samblackk fixed this with a stacked line chart ^^. This is merged for v0.10.1 :tada:
