### ISSUE TITLE
Cannot change roles from Orbit

### ISSUE THREAD

**Issue by petedejoy** [astronomer/astronomer#421]
**Describe the bug**
On Datarouter/current master, changing roles of a user or pending user results in a `DAG Gone It!` when you try to save the updated role. The resulting server error is as follows:
``` Variable "$email" of non-null type "String!" must not be null.```

**To Reproduce**
1. Go to datarouter `Users` screen
2. Click on a new or pending user
3. Change role
4. Click `Update`

**Comment by ryw** [comment]
hotfix in latest release https://github.com/astronomer/orbit-ui/commit/cb3e2906a8ab44c710bb5f36773585ad01cf3884

**Comment by petedejoy** [comment]
@ryw I believe that just addressed an error with deleting users- changing roles would still be messed up since the object that was throwing the error was independent of that fix.

**Comment by ryw** [comment]
Sounds like maybe we need https://github.com/astronomer/orbit-ui/pull/137 to resolve this issue

**Comment by petedejoy** [comment]
Closed by merge. Thanks @ashb!
