### ISSUE TITLE
Admin Panel issues

### ISSUE THREAD

**Issue by schnie** [astronomer/astronomer#426]
- [x] Admin panel only shows self
- [x] User list didn't update after sending invite
- [x] User list didn't update after deleting invite
- [x] Seach box for user list doesn't seem to work
- [x] Clicking on user (myself) throws a "DAG Gone It" with this in the console: `[GraphQL error]: Message: Variable "$workspaceId" of required type "Uuid!" was not provided.Location: [{"line":1,"column":21}]`
- [x] Can't nav back to workspace from dropdown

**Comment by samblackk** [comment]
@schnie Closed with the nav update pushed earlier.
