### ISSUE TITLE
Can't change role of user for workspace

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#435]
1. Invited Greg to my workspace.
1. Clicked to change his role.
1. "DAG gone it!" — Browser error: `TypeError: Cannot read property ‘admin’ of undefined`

I was able to invite email of non-user and change role just fine.

**Comment by petedejoy** [comment]
Looks like this is coming from some of the new admin stuff- `settings` isn't being passed down as a prop to `Delete` in https://github.com/astronomer/orbit-ui/blob/master/src/modules/users/UserConfigure/index.js , so when the delete component looks for `settings.admin` it's getting undefined. Leaving this to @samblackk - looks like an easy fix, but I'm not super familiar with how that's set up yet.

**Comment by ryw** [comment]
@samblackk you on this one?

**Comment by samblackk** [comment]
@ryw Yep - working through it right now

**Comment by ryw** [comment]
https://github.com/astronomer/orbit-ui/commit/439b3fe2907a225a2b16888e6358c8bc46c4ba60
