### ISSUE TITLE
Layout broken

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#437]
While jobs are running w/ KubernetesExecutor, this view is now messed up:

<img width="1361" alt="Screen Shot 2019-08-20 at 10 14 15 PM" src="https://user-images.githubusercontent.com/4283/63397322-2a156000-c398-11e9-9424-8e18198a8db7.png">

**Comment by schnie** [comment]
That left column has 20% width because it used to be `Container`, then I swapped `Pod` and `Container`. Can bump that to be something higher.

**Comment by samblackk** [comment]
Hotfix - https://github.com/astronomer/orbit-ui/commit/c342cd5f3ba07fadc8c3d76f171f7e3316979b09
