### ISSUE TITLE
Delete user as system admin

### ISSUE THREAD

**Issue by schnie** [astronomer/astronomer#439]
Right now we only have `workspaceRemoveUser` which takes a workspace id as a required arg. This works for deleting a user from a single workspace, but doesn't work when trying to delete a user from the admin panel.

This is a different use-case and should have its own resolver and permission associated with it. It should delete the actual user record and cascade delete the roleBindings for that user. Prisma should make this easy in one operation I think.

**Comment by ryw** [comment]
Can this be 0.10.1?

**Comment by schnie** [comment]
We should probably make it work unless we want to pull the whole admin panel out.

**Comment by samblackk** [comment]
@schnie @ryw PRs opened for this.
