### ISSUE TITLE
Astronomer release-0.10 auth login failed

### ISSUE THREAD

**Issue by icednut** [astronomer/astronomer#446]
**Describe the bug**
Hi, I'm using Astronomer Enterprise at GCP. (Astronomer 0.10)
But I have an error astro-cli login using oauth token.
Error message is workspaceUuid, userUuid, label fields are unknown arguments.

Error message is here.
```
{
  "errors": [
    {
      "message": "Unknown argument \"workspaceUuid\" on field \"workspaces\" of type \"Query\".",
      "locations": [
        {
          "line": 4,
          "column": 4
        }
      ],
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED"
      },
      "level": "ERROR",
      "timestamp": "2019-08-23T08:27:37"
    },
    {
      "message": "Unknown argument \"label\" on field \"workspaces\" of type \"Query\".",
      "locations": [
        {
          "line": 5,
          "column": 4
        }
      ],
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED"
      },
      "level": "ERROR",
      "timestamp": "2019-08-23T08:27:37"
    },
    {
      "message": "Unknown argument \"userUuid\" on field \"workspaces\" of type \"Query\".",
      "locations": [
        {
          "line": 6,
          "column": 4
        }
      ],
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED"
      },
      "level": "ERROR",
      "timestamp": "2019-08-23T08:27:37"
    }
  ]
}
```

**To Reproduce**
1. Open Terminal
2. astro auth login BASEDOMAIN
3. oAuth Token input

**Expected behavior**
Login Success!

**Screenshots**
![](https://i.ibb.co/BtvL4Ky/Screen-Shot-2019-08-23-at-5-43-24-PM.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 10.14.6

**Additional context**

**Comment by vparekh94** [comment]
Hi there! Can you run astro version and let me know what the output is?

**Comment by icednut** [comment]
Oh...My mistake
Astro CLI Version is 0.9.7

```
❯ astro version
Astro CLI Version: 0.9.7
Git Commit: 2cb789323cf5e3825810ef5d0ba03913866090ac
```

**Comment by vparekh94** [comment]
That would explain it!

Run `astro upgrade` and you'll get what you need to install the right version of our CLI. Once you do that, you should be able to authenticate without any issues.

Can you let me know what customer you are with? Will just need to log this in our CRM :)

**Comment by icednut** [comment]
I was using Astronomer for study purpose. I wanted to understand Astronomer by installing it myself. Thank you!
