### ISSUE TITLE
Updating environment variables and AU sliders at same time not possible

### ISSUE THREAD

**Issue by ashb** [astronomer/astronomer#456]
There are two "Update" buttons on the Configure deployment page, one below the environment variables section, and the other below the AU sliders. Each of these only submits the changes to the section of the form it is for.

This means if I add some new environment variables, and scale the sliders, then hit one of the "Update" buttons half of the changes will be lost, with no indication to the user.

Both form sections should be submitted.

**Comment by samblackk** [comment]
@schnie @ryw Was there a specific reason why the "deployment info" and "resources" were put into two separate forms when this module was being built?

**Comment by ryw** [comment]
Don't think so, and definitely seems sloppy as it is... 

* It's important to have a button, because it will redeploy infrastructure... But I think it should be top-right - this would be a good spot for future roll-back feature too. Can we remove middle update button and have the whole page fire on one update action?
* We should move "Deprovision" to it's own tab/view

**Comment by schnie** [comment]
Only certain changes should actually trigger a redployment. For example, changing a resource slider requires it, but changing the name or description is purely in the houston db, so no deploy necessary. I think we have some existing logic around this already.

I think this page was originally inspired by the netlify dashboard or something. I brought it up back in the day but we never did much about it. It can change.

**Comment by ryw** [comment]
Netlify does a better job of separating the sections. I don't hate it, but not sure it's better than separate forms per view.

![2019-09-03 14 39 50](https://user-images.githubusercontent.com/4283/64199706-e40cd180-ce58-11e9-8f2b-745b4f252877.gif)

**Comment by schnie** [comment]
@samblackk fixed this and its merged for v0.10.1 :tada:
