### ISSUE TITLE
Extra AU mismatch

### ISSUE THREAD

**Issue by schnie** [astronomer/astronomer#469]
@samblackk looks like when you choose the kube executor for a new deployment and then follow up by configuring the extra au slider down to 0, we get out of sync. I think the database update goes through and sets extra au to 0, so it shows up correctly in the UI, but then it deploys to helm with the extra 10 au padded in from here: https://github.com/astronomer/houston-api/blob/ad4ea3adb4e17f3a66934f5cee0ea9eed5257251/src/lib/deployments/config/index.js#L190.

Maybe we should add some logic in orbit to prevent the user from dragging down to 0 if kube is selected, and possibly add some additional validation logic to the `updateDeployment` call to prevent as well.

**Comment by samblackk** [comment]
Whipping up a fix for this

**Comment by schnie** [comment]
@samblackk thinking we may want to also block this at the API layer. We have some validation logic now, so maybe we could reuse it and add a little part for this.
