### ISSUE TITLE
Airflow Deployment CPU / Mem Usage Unavailable

### ISSUE THREAD

**Issue by ianstanton** [astronomer/astronomer#471]
* CPU and memory usage graphs are empty in both Orbit UI and Grafana
* This was previously working in 0.9.X, but not in 0.10.X

![image](https://user-images.githubusercontent.com/8935584/64662171-109e8b80-d40d-11e9-8009-caad84ad0c61.png)

![image](https://user-images.githubusercontent.com/8935584/64662060-b00f4e80-d40c-11e9-8546-552b73202f07.png)

**Comment by schnie** [comment]
@ianstanton any idea what's causing this? Think we can fix for v0.10.1? If I had to take a random guess without looking, it may be due to the way we changed our container names in the helm charts. Maybe we need to adjust a query to adapt.

**Comment by ianstanton** [comment]
That's what I'm thinking too https://github.com/astronomer/helm.astronomer.io/pull/165/files.

**Comment by ianstanton** [comment]
It looks like either the regex here will need to change or we'll have to use something other than `component_name` in our queries:
```
            # This will patch up most metrics
          - source_labels: [container_name]
            regex: "^(.*-.*-[0-9]{4})-(.*)$"
            replacement: "$1 $2"
            target_label: component_name
```

https://github.com/astronomer/helm.astronomer.io/blob/554e8bf65c40cc83bb941ce9b99a43aef700e710/charts/prometheus/templates/prometheus-config-configmap.yaml#L260-L264

**Comment by schnie** [comment]
Closed via https://github.com/astronomer/helm.astronomer.io/pull/189
