### ISSUE TITLE
Helm deployment uses tiller

### ISSUE THREAD

**Issue by jackskj** [astronomer/astronomer#581]
With release of helm v3 and terraform helm provider v1, tiller is deprecated.
It's highly preferred to use tiller-less deployments for the future. 
Is it possible to deploy this chart without global.helmHost?

**Comment by schnie** [comment]
Hey @jackskj, we have just about finished the work to get our provisioning component, Commander upgraded to use helm 3. We'll be polishing that work up and should be able to merge/release it soon.

cc @vishwas-astro @andriisoldatenko

**Comment by deiga** [comment]
@schnie Do you have a rough timeline for when "soon" would be?

**Comment by jackskj** [comment]
I would really like to see this feature as i moved everything to helm 3 and do not wish to have anything in v2 since that requires tiller

**Comment by schnie** [comment]
Hey @deiga and @jackskj, we are close to releasing 0.13 and are starting work on 0.14, where we have official helm3 support slated to ship. Right now we're targeting the middle of May for that release.
