### ISSUE TITLE
when KEDA is enabled, celery workers go on dynamic node pool

### ISSUE THREAD

**Issue by sjmiller609** [astronomer/astronomer#606]
We are about to turn on KEDA in cloud. Since the worker pods are now dynamic, we should put them on the dynamic node pool.

**Comment by sjmiller609** [comment]
wrong board

**Comment by vishwas-astro** [comment]
@sjmiller609 is this still something valid for KEDA? Should the celery worker pods go in the dynamic node pool instead of the mt node pool? If so, please reopen.

**Comment by vishwas-astro** [comment]
@sjmiller609 please look at this and let me know if this is something that is still valid for KEDA and not working as intended?
