### ISSUE TITLE
Error: release <release-name> failed: secrets "astronomer-bootstrap" already exists

### ISSUE THREAD

**Issue by dbsanfte** [astronomer/astronomer#671]
I'm attempting to install the Helm template for v0.12.8, following the directions to create the astronomer-bootstrap secret before installation of the Helm template, but getting this error when attempting to deploy it:

`Error: release <release-name> failed: secrets "astronomer-bootstrap" already exists`

It seems like the Helm template is trying to recreate the astronomer-bootstrap secret?

**Comment by dbsanfte** [comment]
Docs here definitely say to create the astronomer-bootstrap secret before installing the template:

https://www.astronomer.io/docs/ee-installation-aks/

/shrug

**Comment by schnie** [comment]
Hey @dbsanfte, in 0.12.x we had this flag set to true https://github.com/astronomer/astronomer/blob/release-0.12/values.yaml#L34-L36.

In 0.13.x we fixed this issue by setting it to `false` by default.

The chart is trying to create the boostrap secret itself, and point to a default postgres that is baked in.

I'd suggest either setting that flag to `false`, or upgrade to 0.13 branch.

**Comment by dbsanfte** [comment]
Okay thanks. I will try that.

**Comment by dbsanfte** [comment]
Thanks - this worked. I was able to set it in my config.yaml's global section.
