### ISSUE TITLE
Not able to access airflow_db using Kubernetes executor

### ISSUE THREAD

**Issue by Madhurima333** [astronomer/astronomer#947]
while trying to access airflow db from astro cloud we are getting the below error :

```
Running <TaskInstance: export_airflow_tables.export_tables 2020-11-19T00:00:00+00:00 [running]> on host exportairflowtablesexporttables-aeda73520d844b72a437b4cade256fa
The conn_id `airflow_db` isn't defined
Marking task as UP_FOR_RETRY. dag_id=export_airflow_tables, task_id=export_tables, execution_date=20201119T000000, start_date=20201120T034512, end_date=20201120T034517
Task exited with return code 1
```
This issue is occurring only while using the kubernetes executor, and working fine with celery and local executors.
Ref doc : https://www.astronomer.io/docs/cloud/stable/customize-airflow/access-airflow-database/

Steps that we followed for testing:
1. As per the above documentation copied the Dag code and deployed on staging.
2. With Airflow v1.10.12 and kubernetes executor. 

Ref Tickets:  https://astronomer.zendesk.com/agent/tickets/3068
                    https://astronomer.zendesk.com/agent/tickets/3083

**Comment by kaxil** [comment]
closed by https://github.com/astronomer/airflow-chart/pull/161
