### ISSUE TITLE
cannot terminate aws cert at the elb

### ISSUE THREAD

**Issue by 45cali** [astronomer/astronomer#999]
Using the nginx chart I do not see a way to terminate the cert at the elb.  This would allow us to not have to deal with managing the cert renewal inside kubernetes.

**Comment by danielhoherd** [comment]
Related to https://github.com/astronomer/astronomer/pull/1024

**Comment by rbankston** [comment]
@45cali This is available as of 0.23.13 please reach out via a ticket if you need help configuring this.
